merge with SpaceK33z
wilix-team/iohook pull request #446
Opened 2024-05-10 15:31 UTC by Duangboudda

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-05-10 15:31 UTC, Duangboudda commented
Merge original iohook with SpacK33z fork

2024-05-11 23:37 UTC, lacymorrow commented
Hello!
Could you tell us a bit more about this PR?

2024-05-12 00:48 UTC, lacymorrow requested changes

2024-05-12 00:48 UTC, lacymorrow commented on install.js
> +    'https://github.com/SpaceK33z/iohook/releases/download/v' +
Should we be referencing this?

2024-05-12 00:48 UTC, lacymorrow commented on package.json
> +  "name": "@spacek33z/iohook",
update

2024-05-12 00:48 UTC, lacymorrow commented on package.json
> +  "version": "0.12.0",
update

2024-05-12 00:48 UTC, lacymorrow commented on package.json
> +      "103"
why are we dropping support for old versions here?

2024-05-12 03:00 UTC, Duangboudda commented
Hi,

Sorry,

I made PR by mistake; I meant to merge into repo that I forked, so that I can see the different

Thanks
Tong
________________________________
From: Lacy Morrow ***@***.***>
Sent: Saturday, May 11, 2024 5:49 PM
To: wilix-team/iohook ***@***.***>
Cc: Duangboudda ***@***.***>; Author ***@***.***>
Subject: Re: [wilix-team/iohook] merge with SpaceK33z (PR #446)


@lacymorrow requested changes on this pull request.

________________________________

In .github/workflows/ci.yml<https://github.com/wilix-team/iohook/pull/446#discussion_r1597522131>:

> @@ -11,27 +11,33 @@ jobs:
   ci:
     strategy:
       matrix:
-        os: [ubuntu-latest, macos-latest, windows-latest]
+        os: [ubuntu-latest, macos-latest, windows-2019]


Why are we pinning 2019 here?

________________________________

In .github/workflows/ci.yml<https://github.com/wilix-team/iohook/pull/446#discussion_r1597522256>:

>          arch: [x86_64]
         include:
-          - os: windows-latest
-            arch: i686
+          - os: macos-latest
+            arch: arm64


I think we should keep testing against i686
os: windows-latest
arch: i686

________________________________

In install.js<https://github.com/wilix-team/iohook/pull/446#discussion_r1597528225>:

> @@ -31,7 +31,7 @@ function install(runtime, abi, platform, arch, cb) {

   console.log('Downloading prebuild for platform:', currentPlatform);
   let downloadUrl =
-    'https://github.com/wilix-team/iohook/releases/download/v' +
+    'https://github.com/SpaceK33z/iohook/releases/download/v' +


Should we be referencing this?

________________________________

In package.json<https://github.com/wilix-team/iohook/pull/446#discussion_r1597528273>:

> @@ -1,16 +1,16 @@
 {
-  "name": "iohook",
-  "version": "0.9.3",
+  "name": ***@***.***/iohook",


update

________________________________

In package.json<https://github.com/wilix-team/iohook/pull/446#discussion_r1597528281>:

> @@ -1,16 +1,16 @@
 {
-  "name": "iohook",
-  "version": "0.9.3",
+  "name": ***@***.***/iohook",
+  "version": "0.12.0",


update

________________________________

In package.json<https://github.com/wilix-team/iohook/pull/446#discussion_r1597528348>:

>      ],
     [
-      "node",
-      "16.0.0",
-      "93"
+      "electron",
+      "18.0.0",
+      "103"


why are we dropping support for old versions here?

—
Reply to this email directly, view it on GitHub<https://github.com/wilix-team/iohook/pull/446#pullrequestreview-2051268388>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AEPAPF6XIHRKIATFCMMAIZDZB24ABAVCNFSM6AAAAABHQ2PSHOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANJRGI3DQMZYHA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-05-12 03:06 UTC, Duangboudda commented
I was working to get iohook to work with electron 28, and we did get it work. And we want to know that if the codes are safe to use, mostly just scanning code for security reasons.

2024-05-12 03:15 UTC, Duangboudda commented
Yeah, I will close it, and sorry for the mistake. it is great library and we use it in our organization. Currently, we update our electron version to 28, so we found some forked repo to use, but we want to see new committed codes for security purposes.

2024-05-12 03:15 UTC, closed without merging